### ISSUE TITLE
Submit Button Doesn't work Anymore

### ISSUE THREAD

**Issue by jabygit** [RayBB/easy-gmail-scheduler#10]
Hi RayBB, 

You have created an incredible and clean solution! I love the ease of it and I love that I own the code (although really, I'm just using your code).

I've started using it since late November, I only send a couple emails a week, if that. But since Monday December 24, when I click the "Submit" button, nothing happens. Did Google change some authentication requirements? Or maybe one of those github dependent files like moment.min.js have been updated?

The Google Cloud API looks different now than compared to your screenshots. 
The screen has an "Info" that says:
To use this API, you may need credentials. Click 'Create credentials' to get started.
![google cloud gmail api](https://user-images.githubusercontent.com/46171535/50460218-1e28e980-0942-11e9-87d6-95bab1ee4f93.png)

Chrome's Developer Tools Options shows an error "blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource."
![cors_error](https://user-images.githubusercontent.com/46171535/50460255-6811cf80-0942-11e9-8f84-13a95ba968af.png)

I'm not sure if the Gmail API changed from before. Also, I'm not sure if this CORS error was there before or not. Everything used to just work.

Thanks in advance.

**Comment by RayBB** [comment]
Hey thanks for writing such a great detailed report about the issue.
Everything is still working for me (on the live demo) and I can schedule emails without problem.

I see that the GUI has changed and will have to update that sometime but it shouldn't have broken anything if you already had it working.

I'm not sure why you'd get the CORs error but I'm not getting it. Have you changed anything in the code at all?

I followed the setup instructions on my own computer again from scratch and it all still seems to be working. Try following the steps again to re setup and see if that works?

If not we can take it from there and I'll help you further debug.
