### ISSUE TITLE
Mailtrack.io support

### ISSUE THREAD

**Issue by rad182** [RayBB/easy-gmail-scheduler#2]
Hi,

Thanks for sharing this awesome app. I'm having some problems with this using mailtrack. When I send an email the mailtrack code is being removed. By any chance you can support this?

TIA

**Comment by RayBB** [comment]
I've never used mailtrack but from my brief searches it looks like they embed a tracking image into the email so they can tell when the recipient has read it.

I suspect the problem might be that they only actually inject that code when you hit send, not just when you save a draft. If that's the case, I'm afraid there isn't going to be much I can do.

I'd suggest you email mailtrack support and tell them about this situation. They might have a way to add a tracking code sooner and that would resolve the problem. 

Let me know if you hear from them

**Comment by rad182** [comment]
Thanks for the fast response!
I tried sending it using scheduler, and the mailtrack html text is still intact (for free version. I was using premium one earlier so this one is not visible).
See attached image.
![pasted image at 2017_08_22 01_33 am](https://user-images.githubusercontent.com/71201/29531901-46ed74e6-86dd-11e7-9852-61fc628aee95.png)

Checked the received email source code also, and the tracking code is still there. But for some reason mailtrack.io html code isn't rendered or loaded on the receivers side. Maybe html tags being stripped... I'm not really sure what's happening. Do you have an idea?

**Comment by ChristopherDavenport** [comment]
This may have to do with rendering into text rather than into a Multipart with `text\html`

**Comment by RayBB** [comment]
@rad182 The script has been updated and should be able to work now. Could you try grabbing the latest version and see if it works? Just note that the new setup requires additional authorization

**Comment by sephwork** [comment]
Tried the updated scripts, together with the new authentication instruction. Mailtrack is still not working. Also, the link to your authentication instruction should be:
https://github.com/RayBB/easy-gmail-scheduler#authorization

**Comment by RayBB** [comment]
@sephwork @rad182 Well I'm not really sure what else it could be if it's not working even with the gmail API. Maybe you could ask the Mailtrack customer support if they have any ideas?

**Comment by sephwork** [comment]
Already did, but got a 'we're working on it' type of response:

"Unfortunately, MailTrack is not compatible at the moment with the scheduling functionality of other apps, although this is something that has been discussed with our developers and is on their To-Do list. Apologies for any inconvenience this causes."
