### ISSUE TITLE
No HTML file named Index was found.

### ISSUE THREAD

**Issue by jarsworldcom** [RayBB/easy-gmail-scheduler#4]
Hi,

Not sure if this is the best way, but I had the following.

I get the following error after intitally publishing:
"No HTML file named Index was found. (line 110, file "Code", project "Email Sched")"

Changed line 110 to     return HtmlService.createHtmlOutputFromFile('Index.html') to make it work.

**Comment by RayBB** [comment]
That error would be caused if the file you created wasn't called "Index.html" in your project.

Please check the file doesn't have a lowercase i or other misspelling.
