### ISSUE TITLE
Drafts unable to be sent

### ISSUE THREAD

**Issue by Dputz** [RayBB/easy-gmail-scheduler#8]
I upgraded the latest version of Gmail and just started having issues with this awesome program.  I receive a email in my inbox, draft a reply, schedule it then archive the email.  It is still in my drafts but i then receive an email that it is unable to be sent.  Any ideas?

**Comment by RayBB** [comment]
I'll have to look into this more.
Has it happened multiple times and does it stop happening if you switch to the old gmail again?

I might end up needing to make a new little sidebar widget for the new Gmail.
