### ISSUE TITLE
Frontend styles.css & script.js files?

### ISSUE THREAD

**Issue by foodfan** [RayBB/easy-gmail-scheduler#9]
Hi, thanks for making this! Works great. Question - is there a need for the frontend styles.css and script.js files? What do they do and how do we deploy them? Nothing in the instructions or readme about them.

Thanks!

**Comment by RayBB** [comment]
Hey @foodfan good question, the way it's setup the application actually just pulls the CSS straight from github each load. I think you could just put them as files in your app script and link to them from there but I'm not entirely sure.

To answer that what and how, the CSS just makes everything look nice and the JS is what allows for the frontend to work.

Short answer: you don't really need to worry about them :)
